services:
  # Backend Service
  - type: web
    name: edtube-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
    plan: free

  # Frontend Service
  - type: web
    name: edtube-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -p $PORT
    envVars:
      - key: REACT_APP_API_URL
        value: https://edtube-backend.onrender.com/api
    plan: free
