services:
  # Backend Service
  - type: web
    name: edtube-backend
    runtime: java
    rootDir: backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
    plan: free

  # Frontend Service
  - type: web
    name: edtube-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://edtube-backend.onrender.com/api
    plan: free
